name: isometrik_chat_flutter
description: A new Flutter plugin project.
version: 1.0.0
publish_to: none
homepage: https://github.com/appscrip-3embed/flutter_appscrip_chat.git

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  app_settings: ^7.0.0
  audioplayers: ^6.1.2
  azlistview: ^2.0.0
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  crypto: ^3.0.6
  custom_will_pop_scope: ^2.1.1
  dio: ^5.8.0+1
  emoji_picker_flutter: ^4.4.0
  encrypt: ^5.0.3
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  flutter_image_compress: ^2.4.0
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.2.3
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^9.0.0
  gal: ^2.3.1
  geocoding: ^4.0.0
  geolocator: ^14.0.0
  get: ^4.7.3
  google_maps_flutter: ^2.10.0
  hive: ^2.2.3
  html: ^0.15.5
  http: ^1.3.0
  image: ^4.5.2
  image_cropper: ^11.0.0
  image_painter: ^0.7.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  just_audio: ^0.10.0
  mqtt_client: ^10.7.0
  mqtt_helper:
    git:
      url: https://github.com/rahulsaryam/mqtt_helper.git
      ref: main
  open_filex: ^4.6.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdfx: ^2.9.0
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  plugin_platform_interface: ^2.1.8
  pull_to_refresh: ^2.0.0
  record: ^6.0.0
  scroll_to_index: ^3.0.1
  share_plus: ^12.0.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  video_compress: ^3.1.4
  video_player: ^2.10.0
  video_trimmer: ^5.0.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.isometrik_chat_flutter
        pluginClass: IsometrikChatFlutterPlugin
      ios:
        pluginClass: IsometrikChatFlutterPlugin
      web:
        pluginClass: IsometrikChatFlutterWeb
        fileName: isometrik_chat_flutter_web.dart

  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/background_images/
